### ISSUE TITLE
 Change dataset from object to array of dataset objects

### ISSUE THREAD

**Issue by shepazu** [Inclusio-Community/json-image-metadata#15]
We need the ability to have more than one dataset per chart, for a few use cases, including:

1. A chart may have multiple datasets, such as a line chart superimposed over a bar chart, like so:

![image](https://github.com/Inclusio-Community/json-image-metadata/assets/15254/2ba12975-63b3-4abc-a96b-ff9536ecaa8b)

2. A dashboard, especially one where two charts are closely related, may be rendered in a single chart component.

![image](https://github.com/Inclusio-Community/json-image-metadata/assets/15254/c26e908c-24a5-497b-8d52-6640a77208b3)

There are probably other use cases. In general, if there is more than one dataset and any of their facets aren't identical, it should be split into multiple `dataset` elements.

**Comment by jvartanian** [comment]
@shepazu Would it make sense to change the field name to be plural? e.g  `datasets`

**Comment by shepazu** [comment]
That seems sensible. Semantically, it's common to use "dataset" to mean a collection of data tables, but by using the plural for the keyword, it would reinforce for the author that it can contain more than one "table" of data.

**Comment by shepazu** [comment]
Changed in most recent drafts.
