### ISSUE TITLE
Keeping JIM data and graphic fields in sync 

### ISSUE THREAD

**Issue by jmitra2017** [Inclusio-Community/json-image-metadata#17]
This issue relates to a scenario that may arise if the authoring tools allow direct editing of any dataset field (for correcting errors from automatic generation, or modifying a chart using the data fields) 
The authoring tool will need to re-render the graphic and the specification should probably have a field that indicates the lack of sync when such an edit is made to flag the graphic.

**Comment by shepazu** [comment]
Added a section on "Fidelity in dataset representation".
