### ISSUE TITLE
Improve versioning consistency

### ISSUE THREAD

**Issue by crox** [Inclusio-Community/json-image-metadata#59]
Reviewing the document, there is some disagreement about the requirement for a conforming document to indicate the supported JIM version.

In section 2.2 it says it SHOULD have a version, but then says it MUST have the supported JIM version.

In 3.7 it is labeled as OPTIONAL.

These seem to be three different suggestions.

**Comment by shepazu** [comment]
SHOULD means "OPTIONAL, but really, you SHOULD".

I don't see any contradictions, but maybe I'm missing something, or it's unclear.

Here's a breakdown:

> A document conforming to this specification should specify the version number of the specification to which it conforms, in the `jim` key of the `version` block.
 
This places a conformance criteria on a **document**: 

- The document SHOULD include a `version` block with a SemVer value for the `jim` key.

The document doesn't have to, but it's a good idea to include a version. If it does include a version, it must conform to the SemVer of the spec.


> An implementation conforming to this specification must store internally the version number of the specification to which it conforms, and should expose the version number to the end user. If the implementation opens a JIM document which specifies an incompatible version of JIM, the implementation must warn the end user.

This places conformance criteria on an **implementation**: 

- The implementation MUST have an internal representation of the version of the spec it supports
- The implementation SHOULD expose the supported spec version to the user
- The implementation MUST have an internal representation of the version of the spec it supports
- If the implementation opens a document that contains an incompatible version of JIM, it MUST warn the user.

Does that clear it up, or am I missing something?

**Comment by crox** [comment]
That clears it up.  The key is **document** VS **implementation**.  When I reviewed, they were synonymous in my mind (implementation of a document, I guess?).  Thanks!
